version: '3.2'

volumes:
  mysql-data:

services:
  node:
    container_name: monnode-lery
    image: monnode-lery
    ports:
      - "8082:8083"
    restart: always

  mysql:
    image: mariadblery
    container_name: monmysql
    environment:
      MYSQL_ROOT_PASSWORD: "lery"
      MYSQL_DATABASE: "projetWeb"  # Nom de la base de données à créer
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "lery"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadminlery
    container_name: phpmyadmin_container_lery
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "lery"  # Mot de passe root MySQL
    ports:
      - "8083:83"  # Port pour accéder à phpMyAdmin depuis le navigateur
    depends_on:
      - mysql
